site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'work'
    label: 'Work'
    label_singular: 'work'
    folder: 'content/work'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'work/{{slug}}'
    fields:
      - {
          label: 'Work Category',
          name: 'category',
          widget: 'select',
          multiple: true,
          default: 'mixing',
          options:
            [
              { label: 'Mixing', value: 'mixing' },
              { label: 'Boom', value: 'boom' },
              { label: 'Foley', value: 'foley' },
              { label: 'Post', value: 'post' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Sub-Title', name: 'subtitle', widget: 'string', required: true }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
  - name: 'mixing'
    label: 'Mixing'
    label_singular: 'mixing'
    folder: 'content/mixing'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'mixing/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Price', name: 'price', widget: 'number', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Content', name: 'content', widget: 'markdown', required: true }
  - name: 'rentals'
    label: 'Rentals'
    label_singular: 'rental'
    folder: 'content/rentals'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'rentals/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Price', name: 'price', widget: 'number', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Content', name: 'content', widget: 'markdown', required: true }
  - name: 'about'
    label: 'About'
    files:
      - label: 'Content'
        name: 'content'
        file: 'site/content/about.yml'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Intro', name: 'intro', widget: 'string', required: true }
          - { label: 'Cover Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
          - { label: 'Content', name: 'body', widget: 'markdown', required: true }
          - {
              label: 'Gallery',
              name: 'galleryImages',
              widget: 'list',
              summary: '{{fields.image}}',
              field: { label: Image, name: image, widget: image },
            }
  - name: 'jokes'
    label: 'Jokes'
    label_singular: 'Joke'
    folder: 'content/jokes'
    create: true
    format: 'frontmatter'
    fields:
      - { label: 'Joke', name: 'joke', widget: 'string', required: true }
