site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'jokes'
    label: 'Jokes'
    label_singular: 'Joke'
    folder: 'content/jokes'
    create: true
    format: 'frontmatter'
    fields:
      - { label: 'Joke', name: 'joke', widget: string, required: true }
  - name: 'work'
    label: 'Work'
    label_singular: 'work'
    folder: 'content/work'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'work/{{slug}}'
    fields:
      - {
          label: 'Work Category',
          name: 'category',
          widget: 'select',
          multiple: true,
          default: 'mixing',
          options:
            [
              { label: 'Mixing', value: 'mixing' },
              { label: 'Boom', value: 'boom' },
              { label: 'Foley', value: 'foley' },
              { label: 'Post', value: 'post' },
            ],
        }
      - { label: Title, name: title, widget: string, required: true }
      - { label: 'Sub-Title', name: subtitle, widget: string, required: true }
      - { label: 'Cover Image', name: cover, widget: image, required: true, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
  - name: 'services'
    label: 'Services'
    files:
      - label: 'Content'
        name: 'content'
        file: 'content/services/content.json'
        fields:
          - label: "Mixing"
            name: 'mixing'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: true }
              - { label: 'Sub-Title', name: subtitle, widget: string, required: true }
              - { label: 'Cover Image', name: cover, widget: image, required: true, allow_multiple: false }
              - label: 'Types'
                name: 'types'
                widget: 'list'
                summary: '{{fields.type}} - {{fields.pricing}}'
                fields:
                  - { label: 'Type', name: type, widget: string }
                  - { label: 'Pricing', name: 'pricing', widget: string }
          - label: Rentals
            name: rentals
            widget: 'object'
            fields:
              - { label: 'Title', name: title, widget: string, required: true }
              - { label: 'Sub-Title', name: subtitle, widget: string, required: true }
              - { label: 'Cover Image', name: cover, widget: image, required: true, allow_multiple: false }
              - label: Categories
                name: categories
                widget: 'list'
                summary: '{{fields.name}}'
                fields:
                  - { label: 'Name', name: name, widget: string }
                  - label: Items
                    name: items
                    widget: 'list'
                    summary: '{{fields.name}} - {{fields.price}}'
                    fields:
                    - { label: 'Name', name: name, widget: string }
                    - { label: 'Price', name: price, widget: string }
  - name: 'about'
    label: 'About'
    files:
      - label: 'Content'
        name: 'content'
        format: 'json'
        file: 'content/about/content.json'
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: 'Intro', name: 'intro', widget: string, required: true }
          - { label: 'Cover Image', name: cover, widget: image, required: true, allow_multiple: false }
          - { label: 'Body Image', name: 'bodyimage', widget: image, required: true, allow_multiple: false }
          - { label: 'Content', name: 'body', widget: 'markdown', required: true }
          - {
              label: 'Gallery',
              name: 'galleryImages',
              widget: 'list',
              summary: '{{fields.image}}',
              add_to_top: true,
              field: { label: Image, name: image, widget: image },
            }
  - name: 'policies'
    label: 'Policies'
    files:
      - label: 'Privacy Policy'
        name: 'privacypolicy'
        format: 'yml'
        file: 'content/policies/privacy-policy.yml'
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown', required: true }
      - label: 'Terms of Service'
        name: 'termsofservices'
        format: 'yml'
        file: 'content/policies/terms-of-service.yml'
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown', required: true }
  - label: 'Settings'
    name: 'settings'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/settings/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }